CREATE TABLE IF NOT EXISTS products (
  id TEXT PRIMARY KEY,
  nombre TEXT NOT NULL,
  precio REAL NOT NULL
);

CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    fullname TEXT NOT NULL,
    username TEXT NOT NULL,
    password TEXT NOT NULL,
    role TEXT NOT NULL
);